### ISSUE TITLE
Could releases be created?

### ISSUE THREAD

**Issue by 030** [while-true-do/ansible-role-cockpit#14]
Please create tags to prevent "bump into breaking changes" while updating the role.

**Comment by daniel-wtd** [comment]
@030 It's planned to have such stuff in place and even branch the stable to prevent "breaking changes".

For now it's still in discussion.

@donvipre What do you think about different version information provided in nc/wtd-share/ansible?

**Comment by donvipre** [comment]
@daniel-wtd: yes, i would agree on having a chat.

**Comment by daniel-wtd** [comment]
Discussion occured yesterday.
This issue will stay open until a version is assigned. As a requirement, I have opened the document issue:
https://github.com/while-true-do/community/issues/18

The PR with the initial draft for a version document is also done here: 
https://github.com/while-true-do/community/pull/19

**Comment by daniel-wtd** [comment]
release 0.1.0 released according to the new guidelines, this is a development release.
